### ISSUE TITLE
Vlocity Document Templates need manual activation after deploy

### ISSUE THREAD

**Issue by microweii** [swongcopado/dxcau2vlocity#15]
Hi, hope you don't mind me logging some of the issues here; might be easier to group comms and track.

We've managed to get Vlocity Document Templates deployable through Copado, but it seems like we still need to manually activate them.
Promotion P00157 is one of the latest ones that went from TEST > Prod. You can see below that they're not active.
![image](https://user-images.githubusercontent.com/71686297/183335802-58314fdd-6e0b-41c9-bd36-3c27fc0b0ea5.png)

Maybe there's some insight in the logs?

**Comment by swongcopado** [comment]
This thread is a little bit old but I think might still be relevant:
https://github.com/vlocityinc/vlocity_build/issues/83

Basically, it looks like VBT doesn't support auto-activation of Document Templates.

See this: https://github.com/vlocityinc/vlocity_build#automation-quick-guide

Auto compilation of LWC Omniscripts and Cards is what VBT supports and this is what Copado uses to activate Omniscripts and Flexcards.

**Comment by microweii** [comment]
Gotcha, so not much we can do here. Will close this one then.
