### ISSUE TITLE
"Get Vlocity Dependencies" misses some items (OmniScripts, FlexCard and images)

### ISSUE THREAD

**Issue by microweii** [swongcopado/dxcau2vlocity#16]
Summarising the dependencies that are missed when using "Get Vlocity Dependencies" function.

When these are selected | The following dependencies are missed
-|-
Calculation Procedure | Calculation Procedure Version
Calculation Matrix | <li>Calculation Matrix Version <li> Calculation Matrix Dimensions
FlexCard | <li> Child FlexCard <li> Images
OmniScript | Reusable OmniScripts

Note: These are still deployable when manually selected.

**Comment by swongcopado** [comment]
Hi Michael,
I think there's some issue with the Vlocity setup in the trial environment that is just causing a lot of these potentially false positives. 

Over the weekend, I actually provisioned one of the Vlocity orgs from Salesforce and setup Copado to connect to this environment. In this environment I could get the dependent flexcards without issue.

See these 2 videos.
https://drive.google.com/file/d/1ZuHfWkbsDP8zDX1Xodf6fRkUE62mwwTf/view?usp=sharing
https://drive.google.com/file/d/1mtOImZqcAvOGO2ElgDJQ0yDI2afEok_p/view?usp=sharing

I am wondering if you could try setting up IDX and see if the same issue exists when doing the data pack process through IDX?

**Comment by microweii** [comment]
Hmm, the Vlocity installation could be incomplete and contribute to at least some of the issues here.

I notice in those videos that it also grabbed an OmniScript - is that one marked as "Reusable"?

Also, can I copy those videos for our internal reference (as demonstrative proof it can work)?

**Comment by swongcopado** [comment]
So, just to update... Flexcard and child flexcards seem to work in my org. I am still not sure why it is not working in the trial env. 

Images - I can reproduce this but do you know how Vlocity handles these uploads? Does it just become a static resource in Salesforce? I don't see any new StaticResource metadata type created.

To your question, the Omniscript that got selected is not tagged as Reusable. I haven't tested Reusable Omniscript. 

Yes, please feel free to use the videos.

**Comment by microweii** [comment]
>  do you know how Vlocity handles these uploads? Does it just become a static resource in Salesforce? I don't see any new StaticResource metadata type created.

I believe they're located in the _Documents_ object, in the _Vlocity Document Uploads_ folder (accessible in classic mode):
![image](https://user-images.githubusercontent.com/71686297/183542770-96665d76-4b54-4db7-9e65-2b0368d2f729.png)
(screenshot is in dev1)

**Comment by swongcopado** [comment]
I think I've found the issue. Content assets need to be added to the Assets Library under the Files tab. 
![image](https://user-images.githubusercontent.com/107082678/183549529-374a7945-03ce-4b25-b81f-34efdd611dde.png)

Once added the content to the Asset Library, you can see a tag next to the file that says Asset File. When it has this, in the Commit Grid, you will see the file appear as ContentAsset metadata type.
![image](https://user-images.githubusercontent.com/107082678/183549564-02788c91-0d01-4dbb-8e12-b432b49c10cd.png)


Commit it together with the Flexcard and deploy and it should work. I've tested with images in US-0000078. The Flexcard name is TestFlexcardWithImages.

Please test this out.

**Comment by microweii** [comment]
I was looking at that US in Test and I do see the asset files have come across, as well as the FlexCard.
But the FlexCard is missing the image file and reference:

![image](https://user-images.githubusercontent.com/71686297/183557349-7165c41d-298f-49a5-901e-acee6740506a.png)

For comparison: Dev version has the image reference:
![image](https://user-images.githubusercontent.com/71686297/183557465-a099439c-9913-4d8f-8da4-a8250f7ecf01.png)

So not sure what happened with yours.
That said, I took a couple tries replicating this on my own, and managed to deploy flexcard with the image inside if the image file already exists in both orgs:
![image](https://user-images.githubusercontent.com/71686297/183562416-96593009-39fe-4f3b-98a6-277ea8a259b0.png)

Tried again with a new content asset image to deploy together and this also seems to work:
![image](https://user-images.githubusercontent.com/71686297/183563630-5805d523-c514-4d5b-820e-7f8dcb9e46b1.png)

Will do a bit more testing on FlexCard images but looks like your suggestion for this part works.

Have you been able to collect Calculation Matrix Dimensions using the dependencies getter in your separate org?

**Comment by swongcopado** [comment]
I think you were looking at the wrong Flexcard. The one that is working is TestFlexcardWithImage. 

Yeah, I tested with the Document with image inside the Step of an Omniscript and its working fine as well.
Omniscript: test/userStory82

Haven't tested the Calculation Matrix Dimensions... Do you know if that is something that works with VBT?

**Comment by microweii** [comment]
> I think you were looking at the wrong Flexcard. The one that is working is TestFlexcardWithImage.

Woops, my bad. Anyways I can confirm the workaround for FlexCard images works Dev1>Test>Prod 😄 

> Yeah, I tested with the Document with image inside the Step of an Omniscript and its working fine as well.
Omniscript: test/userStory82.
Also for the Omniscript, the image seem to transfer nicely without a need to add it to the Asset Library.

Yep so the way you added the image in the OmniScript loaded it in the Vlocity Documents Upload folder:
![image](https://user-images.githubusercontent.com/71686297/183575674-1a05a7d2-133c-42d3-a455-dfac15cb2fb0.png)

Deploying the OmniScript by itself from Dev1 > Test still had the image working. I can confirm similarly from another Omniscript (Test/Flexipage; US-0000080)

But using Test/Flexipage again, continuing the deployment from Test > Prod resulted in no image on the OmniScript:
![image](https://user-images.githubusercontent.com/71686297/183575887-c56dca7d-6b83-4943-8098-ccdb5c57bd73.png)
Might be the same for test/userStory82, but I'd like you to try that deployment and confirm.

**Comment by swongcopado** [comment]
I think this is another issue with the inconsistency of the environments in this pipeline. 
I tried it on another pipeline on my side and it deploys well across the environments from DEV to PROD.

**Comment by microweii** [comment]
So going back to the original issue here, if you have time, can you record the scenario (like with the FlexCard) in your other pipeline where:

* Given that there is an OmniScript with a reuseable OmniScript inside,
* When you select the Parent OmniScript in the user story commit screen and click "Get Vlocity Dependencies",
* Then the Reusable OmniScript is also selected?

If that's also shown to work then we can just close this issue (as calculations are tracked separately)

**Comment by swongcopado** [comment]
So, I've just tried doing the reusable Omniscript test in my environment and can confirm that selecting the Omniscript that uses the re-usable Omniscript in the commit grid and clicking Get Vlocity Dependencies will bring in the re-usable Omniscript as well.

Here's the test I did - https://drive.google.com/file/d/1WD104jhcsOtALouLdDVUHCljhCNabEPy/view?usp=sharing

**Comment by microweii** [comment]
Thanks, that's reassuring to know.

I'll close this and the Calculation items can be taken to the separate issue split from this 😄
