### ISSUE TITLE
Vlocity Document Uploads are not deployable

### ISSUE THREAD

**Issue by microweii** [swongcopado/dxcau2vlocity#17]
When a Vlocity document upload is committed into User story branch (e.g. an image as part of OmniScript or FlexCard), attempting to deploy with it will incur an error immediately.

The error looks like:
![image](https://user-images.githubusercontent.com/71686297/183345072-a22ad733-18ab-4fcb-b2d5-9c6b4ecac29f.png)

The files in the commit grid look like:
![image](https://user-images.githubusercontent.com/71686297/183345098-d797a372-0adc-4875-86de-7686881f6695.png)

Note: the FlexCard / OmniScript containing such images can still be deployed but then the resulting component will be missing the image (document) source file.

**Comment by swongcopado** [comment]
Can you share a video on how you upload the document so that I can try it out on my side? Thanks!

**Comment by swongcopado** [comment]
ok. my bad on this one. 

I discovered that the default .gitignore file ignores all commits to the documents folder which is where all of these files are committed as we do not necessarily want to enlarge our git repo with binary files. 

The interesting thing to note is when we do a deployment (even with the documents folder excluded in the .gitignore), Copado can still deploy the Omniscripts with the images intact (other than the issue we saw with deploying to Production yesterday). I believe the VBT packData operation will pull in these resources automatically and there is no need to separately commit them to the repo (hence keeping the repo small).

**Comment by swongcopado** [comment]
I have removed the documents from the .gitignore file and can see the documents uploaded. I also just tried deploying US-000089 and that worked without issues.

**Comment by microweii** [comment]
Oh thanks for that find @swongcopado ; I was actually trying to repro this yesterday (for the video you asked, but I guess you don't need it anymore) but was successfully deploying document uploads (at least .pngs) - was going to test with jpg.

Did you update the .gitignore file via copado? If so, how?

**Comment by microweii** [comment]
I can confirm with US-0000085 that after allowing for Documents to be committed, bundling the OmniScript with the document (images) in the commit have them successfully deploy all the way from Dev1 > Test > Prod.
Demo/DocUpload omniscript in Prod is the result - I've tried various file names as well.
Observable from documents tab as well:
![image](https://user-images.githubusercontent.com/71686297/183813898-6a65122e-2fbe-4078-ae31-7cd19a0bf267.png)

I'll close this but would like to hear back on how the .gitignore file was adjusted in Copado (or was it done in git directly?)
